### ISSUE TITLE
Namespace definition

### ISSUE THREAD

**Issue by naroga** [phpol/phpol#1]
This is a reserved thread so we can discuss which namespace to use.

**Comment by joubertredrat** [comment]
For me is better `Ol\String`, all namespace need to have letter as upcase.

**Comment by naroga** [comment]
IMO, `OL` (all caps) works better to make it clear it's an acronym.

**Comment by joubertredrat** [comment]
> IMO, `OL` (all caps) works better to make it clear it's an acronym.

This is good too, but all downcase isn't good as @lucasmezencio want `ol`.

**Comment by joubertredrat** [comment]
@hernandev will need to fix this on composer after define this.

**Comment by lucasmezencio** [comment]
@joubertredrat I didn't!

**Comment by hernandev** [comment]
@joubertredrat and everyone.

`OL` should be all caps since it's not a word but an acronym.

since each letter stands for a word.

It's `CIA` not Cia or `NSA` not Nsa

**Comment by joubertredrat** [comment]
Let's make this.
 
 :one: =`Ol\String`
:two:  =`OL\String`
:three:  =`ol\String`

@hernandev @naroga @lucasmezencio @marcusagm  vote on this comment.

**Comment by marcusagm** [comment]
I agree! OL all caps

**Comment by hernandev** [comment]
2 - OL All caps

**Comment by joubertredrat** [comment]
2 - OL All caps

**Comment by pedrommone** [comment]
2 - I agree with `OL`, its cleaner.

**Comment by DennyLoko** [comment]
2 - OL All caps

**Comment by lucasmezencio** [comment]
2 - `OL` All caps

**Comment by lucasmezencio** [comment]
Issue closed. Voting closed.
Thanks guys.
