### ISSUE TITLE
Basic contribution specs proposition.

### ISSUE THREAD

**Issue by naroga** [phpol/phpol#10]
I'd like to put a basic contribution and specs proposition up for a vote.

The basic rules should read:

---

The intent of this guide is to reduce friction when working with code written by different authors. It does so by enumerating a shared set of rules and expectations about how to write PHP code.

The style rules herein are derived from de facto standards adopted from the community at large, and commonalities between the voting members. When various authors collaborate across multiple projects, it helps to have one set of guidelines to be used among all those projects. Thus, the benefit of this guide is not in the rules themselves, but in the sharing of those rules.

The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in [RFC 2119](http://www.ietf.org/rfc/rfc2119.txt).

1. Overview

* Code MUST adhere to PSR-2.
* Autoloading and file names MUST be PSR-4 compliant.
* Code SHOULD follow Object Calisthenics rules.
* API changes MUST adhere to the Semantic Versioning schema.
* Code MUST be accompanied by its respective unit tests. Full (100%) coverage is expected.

---

Voting should be :+1:, :-1: or self-declared abstentions.
Voting will close when all 7 voting members have cast their votes, or at February 9th 2017, at 9:02 BRST. If no minimum quorum (5 members) is met by then, the vote will fail and will have to be restarted.

**Comment by lucasmezencio** [comment]
What about this proposal?

**Comment by naroga** [comment]
@lucasmezencio we haven't reached the end time, nor the total amount of votes. Please note that non-members have voted in this issue. I'm waiting until everyone has voted.

**Comment by naroga** [comment]
@hernandev hasn't voted yet.

**Comment by hernandev** [comment]
done

**Comment by DennyLoko** [comment]
All voting members have already voted, so this vote has passed.

Summary:

Eligible voters: 8
Quorum: 8
Voting in favor: 8
Voting against: None
Abstaining: None
Result: The vote has passed.
