### ISSUE TITLE
Basic Guidelines for Commit Messages

### ISSUE THREAD

**Issue by lucasmezencio** [phpol/phpol#12]
I'd like to put a basic guidelines for commit messages up for a vote.

The basic rules should read:

---

The intent of this guide is to reduce friction when working with code written by different authors. It does so by enumerating a shared set of rules and expectations about how to write good commit messages to enhance the ability to understand **what**, **how** and **why** people did something.

The guidelines rules herein are derived from many other guidelines for commit messages. When various authors collaborate across multiple projects, it helps to have one set of guidelines to be used among all those projects. Thus, the benefit of this guide is not in the rules themselves, but in the sharing of those rules.

The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in [RFC 2119](http://www.ietf.org/rfc/rfc2119.txt).

### 1. The seven rules of a great Git commit message (the reference is in each rule)

1. [Subject MUST be separated from body with a blank line](http://chris.beams.io/posts/git-commit/#separate)
2. [Subject line MUST be limited by 50 characters](http://chris.beams.io/posts/git-commit/#limit-50)
3. [Subject line MUST be capitalized](http://chris.beams.io/posts/git-commit/#capitalize)
4. [Subject line MUST NOT end with period](http://chris.beams.io/posts/git-commit/#end)
5. [Subject line MUST be using the english imperative mood](http://chris.beams.io/posts/git-commit/#imperative)
6. [Body MUST be wrapped at 72 characters](http://chris.beams.io/posts/git-commit/#wrap-72)
7. [Body MUST be used to explain _what_ and _why_ vs. _how_](http://chris.beams.io/posts/git-commit/#why-not-how)

### 2. Commit messages language

Commit messages MUST be in english.

---

Voting should be :+1:, :-1: or self-declared abstentions.
Voting will close when all 7 voting members have cast their votes, or at February 9th 2017, at 12:20 BRST. If no minimum quorum (5 members) is met by then, the vote will fail and will have to be restarted.

**Comment by naroga** [comment]
What happens if a commit message does not conform to this spec? Can/should/must a PR be rejected on that basis?

**Comment by lucasmezencio** [comment]
@naroga I think that webhooks in main repository may help us with that. What do you think?

**Comment by naroga** [comment]
@lucasmezencio I absolutely agree. Now, I'm not sure we can append this to the main proposition, as some people have already voted. Can you put this up for a vote, separately?

**Comment by hernandev** [comment]
It's nice to have, but I disagree with commit messages having a strict guide.

From where I'm sit, it makes absolutely no difference. If we need rules, let's focus them where they are really important.

**Comment by naroga** [comment]
I agree with softening it all to a SHOULD instead of a MUST, and have it as a general guideline to keep in mind, not something that affects the actual workflow.

**Comment by pedrommone** [comment]
I think it is too much. We need it as a nice to have, if we go further and use it as a `must have` it will be a bit aggressive and scare for outside collaborators.

**Comment by hernandev** [comment]
@pedrommone outside collaborators often don't read the guide lines

**Comment by lucasmezencio** [comment]
@naroga @hernandev thinking deeply, I agree that this proposal must softening to SHOULD instead of MUST.
I will close this issue and open another with modifications.

**Comment by hernandev** [comment]
@naroga @lucasmezencio  I can change my vote to Yes if we agree on SHOULD, not MUST

**Comment by naroga** [comment]
I've withdrawn my YES vote in favour of softening all the requirements, except language (all commits MUST be in english) to a SHOULD

**Comment by lucasmezencio** [comment]
@hernandev @pedrommone the thing I am wanting here is to avoid messages like `Fix`, `Lalala`, `Another fix`.

**Comment by lucasmezencio** [comment]
@everyone proposal closed. Opening another one.

**Comment by hernandev** [comment]
@lucasmezencio we can required external collaborators to squash and ammend whenever they propose something like that
