### ISSUE TITLE
@marcossffilho as Contributor and Voting Member

### ISSUE THREAD

**Issue by hernandev** [phpol/phpol#14]
I'm sponsoring @marcossffilho as voting member.

Yay oy Nay (:+1:)/(:-1:)

**Comment by pedrommone** [comment]
@marcossffilho welcome.

**Comment by naroga** [comment]
Please create a PR with the respective entry on CONTRIBUTORS.md.

**Comment by filhocodes** [comment]
Thanks :smiley:

**Comment by DennyLoko** [comment]
All voting members have already voted, so this vote has passed.

Summary:

Eligible voters: 7
Quorum: 7
Voting in favor: 7
Voting against: None
Abstaining: None
Result: The vote has passed.
