### ISSUE TITLE
Component Licenses

### ISSUE THREAD

**Issue by naroga** [phpol/phpol#15]
Hi! In all the hurry to get coding, we forgot to talk about licenses.

I'd like to open a vote that requires all components to be distributed under the MIT license.

---
Voting should be :+1:, :-1: or self-declared abstentions.
Voting will close when all 7 voting members have cast their votes, or at February 9th 2017, at 15:50 BRST. If no minimum quorum (5 members) is met by then, the vote will fail and will have to be restarted.

**Comment by hernandev** [comment]
MIT required also a Copyright Holder :) Are we putting several lines on it or using a group non-legal name?

**Comment by naroga** [comment]
We can put this up for a vote separately. I'd rather use the group non-legal name: `PHP Object Library - OL`.

**Comment by marcusagm** [comment]
http://opensource.stackexchange.com/questions/4960/can-a-team-be-the-copyright-holder-mit

We can put a non-legal group name with a link to `CONTRIBUTORS.md`

**Comment by hernandev** [comment]
If a team can be owner, it's ok for me, just lets create an general email to use inside composer.json

**Comment by joubertredrat** [comment]
MIT is better, is flexible and expansible.

**Comment by lucasmezencio** [comment]
LGTM.

**Comment by naroga** [comment]
All voting members have already voted, so this vote has passed.

Summary:

Eligible voters: 8
Quorum: 8
Voting in favor: 8
Voting against: None
Abstaining: None
Result: The vote has passed.
