### ISSUE TITLE
Project Style and Default Rules

### ISSUE THREAD

**Issue by hernandev** [phpol/phpol#3]
Suggestion for style and general coding guide:

- PSR2
- Object Calisthenics

Any other ideias?

**Comment by pedrommone** [comment]
@hernandev can you provide some doc about `Object Calysthenics`?

**Comment by lucasmezencio** [comment]
@pedrommone http://williamdurand.fr/2013/06/03/object-calisthenics/#tldr

**Comment by hernandev** [comment]
Ported to PHP https://github.com/object-calisthenics/phpcs-calisthenics-rules

**Comment by filhocodes** [comment]
Are we gonna follow the PHP DateTime way of having both `DateTime` and `DateTimeImmutable`, or the project will stick just to one implementation?

**Comment by naroga** [comment]
Hi! I'd like to talk about some rules for contributing. We should also define a core of contributors. We're putting things up to vote, but we don't even know who are the voting members, and how to count if we have a minimum voting quorum. When is the voting closed? When everyone (and here we'd need a list of contributors) votes, or when a specific amount of time passes?

**Comment by hernandev** [comment]
@naroga core contributors should be based on merits, so I would suggest everyone interested to have an active voice on at least the first month, and we make the core about the ones that made more contributions

**Comment by naroga** [comment]
I'm for adopting PSR-2 and PSR-4, as they're already the de-facto standards, but I'm not sure if I'd like to enforce calisthenics rules. Those should be a general guideline, a SHOULD, not a MUST. Code readability can be enforced through thorough code reviews. Forbidding stuff like two-level indentations and the `else` keyword sounds too harsh for me.

**Comment by hernandev** [comment]
@naroga OC is a nice-to-have, should not be strictly forced by applied when possible

**Comment by naroga** [comment]
@hernandev I agree. I think we should also only consider a feature complete (and able to be merged) if it's accompanied by its respective unit tests.

**Comment by hernandev** [comment]
so, only fully covered code will be merged, that's cool?

**Comment by hernandev** [comment]
it will restrict a little the number of contributors, specially internal, but it's something that will really aggregate value to the project, if we aim to make it popular

**Comment by hernandev** [comment]
Also, I would like to recommend SEMVER

**Comment by naroga** [comment]
Alright. I'd like to put these basic specs up for a vote: SEMVER, PSR-2 and PSR-4. I don't think we'll find much resistance here, since it's pretty standard, but I think it's important to go through the due process.

I'll open a new thread for this vote, and if (when) it passes, I'll create a CONTRIBUTING.md.

**Comment by joubertredrat** [comment]
I think that can be support chained methods too.

**Comment by DennyLoko** [comment]
I'm closing this because the discussions of the style guide and rules were discussed on #10, which has already been voted.
