### ISSUE TITLE
Restart library repositories?

### ISSUE THREAD

**Issue by naroga** [phpol/phpol#5]
Hi! I'd like to propose a removal of all current repositories under the `phpol` namespace (except for this one, `phpol/phpol`, obviously), up until we define which libraries will be created, under which name. We currently have a `String` and `Array` repositories, none of which were voted, some with sample codes on `master`.

**Comment by naroga** [comment]
:+1:

**Comment by lucasmezencio** [comment]
👍

**Comment by pedrommone** [comment]
I like the idea to use `String` as a pilot. I'm against to a `master reset`. I'm in favor of moving the currently examples to an separated branch and PR, and start following the `github-flow`.

**Comment by hernandev** [comment]
for me, go ahead, let's create empty repos, with gitflow+github flow enabled so we can plan which one individually after initial discussion

**Comment by filhocodes** [comment]
@lucasmezencio @naroga maybe we should use reactions to vote instead of single comments cause, unlike GitLab, GitHub doesn't show an emoji counter in the issue.

Also, I agree with @pedrommone

**Comment by naroga** [comment]
This issue is a moot point now. The String spec has been approved (and is being worked on, as we speak), and the `Array` repository has been absorved by the `Collections` repository.

Thus, all repositories and in the proposed state. I'll withdraw this proposal.
