### ISSUE TITLE
Voting members admission - as of right now.

### ISSUE THREAD

**Issue by naroga** [phpol/phpol#6]
Hi! We are currently voting on issues. But I'm not really sure of when to halt the vote. Who are the core members? Who can vote? When is the voting stopped?

My proposal: As of right now, every contributor, independent of merit, should be able to vote on issues. Issues should be held open for 2 days, then the voting is closed. If we reach a consensus before the stipulated date, the issue can be closed. However, to close prematurely, we should have a majority (50% + 1) of votes AND require a vote from every contributor.

Rules and bylaws should require a 2/3 vote, whereas technical votes should require 50% + 1 votes of contributors (not of total votes).

**Comment by pedrommone** [comment]
Agreed.

**Comment by naroga** [comment]
This discussion was moved to PR #7.
