### ISSUE TITLE
String Component

### ISSUE THREAD

**Issue by hernandev** [phpol/phpol#9]
This is the first component Vote, more will follow this one and Votes should be done as per rules defines on this repository.

-- 
## Proposal
Implement the first component as being `OL\String`.

String should be the component responsible for handling anything string related, there was some code samples but the general roadmap will be explained bellow:

#### Part 1
Implement common and most used functions, fully tested 

#### Part 2
Implement less used functions, test for full UTF-8 support 

#### Part 3
Map remaining String functions on PHP Core and decide on it's implementation or not.

## Options:
 Vote in favor of this being the first implemented component:

- :+1: (`:+1: `) for voting Yes.
- :-1: (`:-1: `) for voting No.

Please thumbs up/down on this very message, suggestions and discussion can be made on the comments.

**Comment by filhocodes** [comment]
* Components (title)

**Comment by hernandev** [comment]
thanks @marcossffilho

**Comment by filhocodes** [comment]
At least for part 1, maybe:

 - change case (upper, lower, title, initial, etc)
 - length
 - contains
 - replace
 - slice

**Comment by hernandev** [comment]
@marcossffilho i did most of it already as example, needs refactor but those should not take long to refactor and complete.

**Comment by filhocodes** [comment]
@hernandev I saw in your code you adhere to immutability. The library will adopt as a must be?

**Comment by hernandev** [comment]
@marcossffilho no it was an example, but we need to keep ti consistent between components even

**Comment by filhocodes** [comment]
I prefer we have both, even though I favor immutability instead of the other.

**Comment by marcusagm** [comment]
My suggestions

 - length
 - reverse
 - charAt
 - match
 - slice
 - indexOf
 - split
 - replace
 - trim
 - pad
 - stripTags
 - stripSlashes
 - addSlashes
 - humanize
 - normalize
 - camelize
 - underscore
 - htmlEncode
 - htmlDecode
 - toLower
 - toUpper
 - upperFirst
 - lowerFirst
 - upperWords
 - countWords
 - shuffle
 - newLineToHtmlBreak

**Comment by joubertredrat** [comment]
My suggestions

* escape

**Comment by filhocodes** [comment]
@marcusagm @joubertredrat  It depends much on what will be decided on #4, but I think HTML related like `nl2br`, `encode/decode` should be in a "HtmlString" component.

**Comment by marcusagm** [comment]
make sense

**Comment by pedrommone** [comment]
@marcusagm @marcossffilho HTML component depends a lot, I think is a little of overwhelming for now.

For the whole component, I think basic operations are enough and everything can be expanded with new Components.

**Comment by marcusagm** [comment]
Yep, these functions can wait as weel as functions related with regex (match)

**Comment by hernandev** [comment]
gonna start working on a PR prototype, we can discuss it from there

**Comment by rodrigo-brito** [comment]
Suggestion of functions:
- digits - Only numbers
- letters - Only letters

**Comment by DennyLoko** [comment]
All voting members have already voted, so this vote has passed.

Summary:

Eligible voters: 7
Quorum: 7
Voting in favor: 7
Voting against: None
Abstaining: None
Result: The vote has passed.

**Comment by DennyLoko** [comment]
Now the discussion related to this component should be taken at the relevant PR: phpol/string#1.
